[package]
name = "send_sms"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
failure = "0.1.8"
reqwest = { version = "0.13.3", features = ["blocking", "form", "json"] }
rustlio = "0.1.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = "1.52.1"
twilio = "1.1.0"
